### PR TITLE
remove unnecessary check from tlc2

### PR DESCRIPTION
**Pull request by domsj**
Still waiting for CI

### CODE REVIEW

**Comment by domsj** [comment]
CI is good

**Comment by NicolasT** [comment]
Why is this 'unnecessary'?

**Comment by domsj** [comment]
I don't see how the check is not yet covered by https://github.com/Incubaid/arakoon/blob/1.6/src/tlog/tlc2.ml#L467 , and neither did romain yesterday.
As far as I understand it either the previous entry is already in the next file, in which case the check on L467 would've been true the previous time but not any more this time (as _outer would be incremented already) or the previous entry is in the previous file, in which case if (Entry.i_of pe) = i then the condition on L467 can't be met.

@toolslive also told me that all edge cases related to tlog handling are under test, so I could remove it and verify with the tests wether my initial assumption (this being unneccessary) was correct.
My hope was that removing it would eventually lead to less confusion when people look at that code again.

**Comment by toolslive** [comment]
LGTM

**Pull request merged**
