### PR TITLE
update all copyright notices

### PR DESCRIPTION
**Pull request by domsj**
and sneakily remove an obsolete file

### CODE REVIEW

**Comment by domsj** [comment]
updated

**Comment by toolslive** [comment]
fine. so we'll have to do this again next year?

**Comment by domsj** [comment]
Dunno, you're the one who complained about the wrong year number in another PR.
For all I care we can also remove the year number...

**Comment by toolslive** [comment]
we can also remove the headers and replace it with one single file stating the licensing under src/

**Comment by domsj** [comment]
Hmm .. that would indeed be better.
Now I'm wondering how other projects handle this, will have to do some research.
Maybe iso removing the headers replace them with a pointer to that file?

**Pull request closed without merging**
