### PR TITLE
Ara 56 bis

### PR DESCRIPTION
**Pull request by domsj**
Let's hope it's fixed now

### CODE REVIEW

**Comment by domsj** [comment]
Giving it 1 final CI run http://cimaster.incubaid.com/view/arakoon-git/job/arakoon-git-launcher/366/

**Comment by domsj** [comment]
Bleh, the base tests ain't yet as stable as I would like (No Master failures) ... I'll have a look

**Comment by domsj** [comment]
It looks a bit better now on CI.
Still some failures, of the same kind as those fixed in https://github.com/Incubaid/arakoon/pull/479

**Comment by NicolasT** [comment]
Looks OK.

**Pull request merged**
