### PR TITLE
1.6 for 1.7

### PR DESCRIPTION
**Pull request by NicolasT**
Will run through CI.

@domsj Would you mind performing the manual test for the ticket on this branch?

### CODE REVIEW

**Comment by domsj** [comment]
Still works in my limited test

**Comment by domsj** [comment]
And LGTM

**Comment by NicolasT** [comment]
All CI passed for 7c7bb3a except `quick` which failed due to the missing space fixed in b0c7524. Re-running `quick` now.

**Comment by NicolasT** [comment]
`quick` passed as well (#660).

**Pull request merged**
