### PR TITLE
update META & changelog for 1.7.4

### PR DESCRIPTION
**Pull request by domsj**
also reordered the changelog a bit to make it chronological

### CODE REVIEW

**Comment by NicolasT** [comment]
I'm a bit confused... Why does adding the new entry to the top of the changelog change so many things?

**Comment by domsj** [comment]
A few entries in the changelog were not in chronological order, I 'rectified' that situation (as mentioned in my pull request comment above).
Do you want me to leave the ordering as it was?

**Comment by NicolasT** [comment]
Woops, missed that remark. When doing these changes anyway, maybe get the spacing in sync as well? Some entries have 2 spaces after the name, before '<', some have only one. I don't know what the formatting rules say, but it's somewhat inconsistent now.

**Comment by domsj** [comment]
You're right about those spaces, fixed that.
Do you want me to fix the extra space in your e-mail address too or is that somehow intentional?

**Comment by NicolasT** [comment]
Hmh, never noticed that. Feel free to fix, my bad.

**Comment by domsj** [comment]
No problem, adjusted that too

**Comment by NicolasT** [comment]
Go

**Pull request merged**
