### PR TITLE
Cleanup warnings

### PR DESCRIPTION
**Pull request by domsj**

### CODE REVIEW

**Comment by domsj** [comment]
Still waiting for CI

**Comment by domsj** [comment]
Fyi: There's a failing test related to a not found user_function (which is definitely an error in the test case), but now I'm left wondering how we want to handle that.
(The error in the test case being exposed now is due to the change in exception handling I introduced in store.ml.)

**Comment by domsj** [comment]
Ok, so I changed the behaviour of user_functions as discussed on the chat.
Things look ok on CI, travis failure is camltc related.

**Comment by toolslive** [comment]
it's a dirty job but I'm glad somebody did it. LGTM

**Pull request merged**
