### PR TITLE
Fix 'Invalid record header'

### PR DESCRIPTION
**Pull request by NicolasT**
This pull request should as-is not be merged since it only contains a first change required in order to fix ARAKOON-373 ('Invalid record header' mess).

More changes (to TC internals) will be required later on.

Some initial review would be appreciated though.

### CODE REVIEW

**Comment by domsj** [comment]
Who should be responsible for executing 'git submodule init' and 'git submodule update' to fetch the submodule?
The user? setup_env.py? Do we want to document this somewhere?

**Comment by NicolasT** [comment]
You can clone using the `--recursive` flag ;-)
I guess this should be mentioned in the docs, but it's not up to some script to do it, since we don't use a script which performs the clone either.

**Comment by NicolasT** [comment]
This PR is not ready for merging. TODO:
- [x] Add fixes to Incubaid/tokyocabinet@595a98c20ae and update submodule
- [x] Add `git describe` output from the submodule to `arakoon --version` output & logging
- [x] Update CI to handle submodules (there's a flag in the Git repository configuration section)

**Comment by NicolasT** [comment]
b88e8be is running against 'set B'. If successful, this seems ready for merging (after merging Incubaid/tokyocabinet@079426312 into the 'arakoon' branch and updating the submodule ref if required).

**Comment by NicolasT** [comment]
Test run succeeded. I'll merge the changes into our TokyoCabinet repository, then update the submodule ref in this branch and things are ready for final review.

**Comment by NicolasT** [comment]
Ready for review & merge. 2 failures in CI (_base_):
- _universe.system.elect_master.trivial_master3_: No master
- _universe.messaging.tcp.pingpong_multi_server_: Test took too long

**Comment by NicolasT** [comment]
LGTM from @domsj

**Pull request merged**
