### PR TITLE
log %s is master on consensus of a new master

### PR DESCRIPTION
**Pull request by domsj**

### CODE REVIEW

**Comment by NicolasT** [comment]
Was there a reason for the old log message to be removed?

**Comment by domsj** [comment]
I think it's something romain just forgot in https://github.com/Incubaid/arakoon/commit/163ffecf0458276512bc5296609ec36ffe2d4d62 , I don't see a real reason.

**Comment by domsj** [comment]
updated (rewrote history with new commit)

**Comment by NicolasT** [comment]
LGTM

**Pull request merged**
