### PR TITLE
OVS-1325 - Added support for creating rpm packages

### PR DESCRIPTION
**Pull request by khenderick**
Added support for creating rpm packages

### CODE REVIEW

**Comment by NicolasT** [comment]
Unrelated to whether this should be included in the repo or not (not my call), the patch needs some tweaking to fix authorship information in order to be suitable for merging:

```
From 13a99c86b968d3bcf8a009b5c683f8499cfdc68d Mon Sep 17 00:00:00 2001
From: root <root@saelbrecCentos7.openvstorage.com>
Date: Mon, 29 Sep 2014 16:58:42 +0200
Subject: [PATCH] OVS-1325 - Added support for creating rpm packages
```

Patches should have a 'real' author & valid e-mail address. To fixup, see `man git-commit` (the `--amend`, `--reset-author` and other options, as applicable).

**Comment by khenderick** [comment]
I see, valid point. But since the commit can't be changed anymore, I'll just close this pull request, and request a new pull request with the correct author information.

**Comment by NicolasT** [comment]
Huh, you could fix it in your branch and force-push the fixed patch to your repository, after which the content of this PR should be synced automatically.

**Comment by khenderick** [comment]
I was unaware of that feature, thanks for pointing out.

**Comment by khenderick** [comment]
But it seems I can't reopen & comment because I force-pushed this change.

**Pull request closed without merging**
