### PR TITLE
Batched store optimize range queries

### PR DESCRIPTION
**Pull request by domsj**
Looks good on CI

### CODE REVIEW

**Comment by domsj** [comment]
Hmm, only thinking of it now, but this does break https://github.com/Incubaid/arakoon/blob/1.7/pylabs/test/server/system_tests_common.py?source=c#L179 . (Of which strangely enough we see no noticeable effects when running our test suite, but amplidata does.)
So we might want to make flushing of the store an operation which can be explicitly triggered by clients?

**Comment by toolslive** [comment]
maybe; but only exposed in mgmt api?

**Comment by domsj** [comment]
Ok, exposed the flushStore call in the management API.
CI succeeded.
Also opened a PR for pyrakoon: https://github.com/Incubaid/pyrakoon/pull/5 .

**Comment by toolslive** [comment]
ok

**Pull request merged**
