### PR TITLE
Remove unused `String_extra` module

### PR DESCRIPTION
**Pull request by NicolasT**

### CODE REVIEW

**Comment by toolslive** [comment]
is used in nursery, and 3.0 (prefix_match)

**Comment by NicolasT** [comment]
Indeed it is in 3.0 (so a forward merge will need some care). Not sure about nursery?

```
[nicolas@chi arakoon (1.7 %)]$ git show-ref refs/heads/1.7
891800e81dae4046f2e4286e6b0e6ef176ad60d9 refs/heads/1.7
[nicolas@chi arakoon (1.7 %)]$ git grep prefix_match
src/tools/string_extra.ml:let prefix_match prefix k =
```

**Comment by domsj** [comment]
Another option is moving that function to Std.String

**Comment by NicolasT** [comment]
Agree (in 3.0).

**Comment by domsj** [comment]
Ok, LGTM

**Pull request merged**
