### PR TITLE
Rework `Multi_paxos.update_votes`

### PR DESCRIPTION
**Pull request by NicolasT**
Since it wasn't immediately obvious to me what `Multi_paxos.update_votes` did while reviewing #470, this change attempts to simplify things by introducing a fairly generic `Std.List.alter` function, which is then used to implement `Multi_paxos.update_votes`, hopefully clarifying what this function does exactly.
- [x] Run CI

### CODE REVIEW

**Comment by NicolasT** [comment]
`arakoon-git-base` 348 all blue.

**Comment by domsj** [comment]
LGTM if CI is ok

**Comment by NicolasT** [comment]
`arakoon-git-launcher 399` launched because of merge.

**Comment by NicolasT** [comment]
All blue.

**Pull request merged**
